sudo: required

services:
  - docker

language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  # Deploy a snapshot version only for master branch and jdk8
  - if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" -a "$TRAVIS_BRANCH" == "master" ]; then 
      make && mvn -s settings.xml deploy -DskipTests;
    else
      make linux64 && mvn test;
    fi
