sudo: required

services:
  - docker

language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - make linux64
  - if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" -a "$TRAVIS_BRANCH" == "master" ]; then 
    # build all native libraries and deploy a snapshot version only for master branch and jdk8
    make && mvn -s settings.xml deploy -DskipTests; else
    mvn test;
    fi
