sudo: required

services:
  - docker

language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script:
  - make
  - mvn -s settings.xml deploy -DskipTests

branches:
  only:
    - master
    - develop

